{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-lab-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gke-lab-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
